import type { Metadata } from "next";
import '@/styles/globals.css'
import NavigationLoadingProvider from '@/components/NavigationLoadingProvider';
import Providers from '@/components/Providers';
import AppLayout from '@/components/AppLayout';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Providers>
          <NavigationLoadingProvider>
            <AppLayout>
              {children}
            </AppLayout>
          </NavigationLoadingProvider>
        </Providers>
      </body>
    </html>
  );
}
