import type { Metadata } from "next";
import '@/styles/globals.css'
import NavigationLoadingProvider from '@/components/NavigationLoadingProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* DNS Prefetch for external resources */}
        <link rel="dns-prefetch" href="https://images.unsplash.com" />

        {/* Preconnect to important domains */}
        <link rel="preconnect" href="https://images.unsplash.com" />

        {/* Optimize font loading */}
        <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" />
      </head>
      <body
        className={`antialiased`}
      >
        <NavigationLoadingProvider>
          {children}
        </NavigationLoadingProvider>
      </body>
    </html>
  );
}
