import type { Metadata } from "next";
import '@/styles/globals.css'
import NavigationLoadingProvider from '@/components/NavigationLoadingProvider';
import Providers from '@/components/Providers';
import AppLayout from '@/components/AppLayout';
import { fetchCategories } from '@/lib/fetchCategories';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await fetchCategories();

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`antialiased`}
      >
        <Providers>
          <NavigationLoadingProvider>
            <AppLayout categories={categories}>
              {children}
            </AppLayout>
          </NavigationLoadingProvider>
        </Providers>
      </body>
    </html>
  );
}
